//
// Created by Petr Flajsingr on 19/10/2018.
//

#ifndef FILEDOWNLOADERS_HEADERS_BASEFILEDOWNLOADER_H_
#define FILEDOWNLOADERS_HEADERS_BASEFILEDOWNLOADER_H_

class BaseFileDownloader {

};

#endif  //FILEDOWNLOADERS_HEADERS_BASEFILEDOWNLOADER_H_
