//
// Created by Petr Flajsingr on 19/10/2018.
//

#ifndef FILEDOWNLOADERS_HEADERS_FILEDOWNLOADOBSERVER_H_
#define FILEDOWNLOADERS_HEADERS_FILEDOWNLOADOBSERVER_H_

class FileDownloadObserver {

};

#endif  //FILEDOWNLOADERS_HEADERS_FILEDOWNLOADOBSERVER_H_
